
services:
    mongodb:
        image: mongo:8.0.0
        container_name: blog-mongodb
        restart: always
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_DATABASE: blog
        volumes:
            - mongodb_data:/data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/blog --quiet
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    mongodb_data:
        driver: local
